### ISSUE TITLE
Locations not syncing from TaxCloud

### ISSUE THREAD

**Issue by JoshuaC215** [bporcelli/simplesalestax#160]
I recently re-activated the Simple Sales Tax plug-in on my store after having it disabled for some time. In the meantime, the primary shipping location had changed on my business, which I recently updated in TaxCloud.com for my account (PO Box to a permanent address).

After re-activating, my ID and key from TaxCloud were still saved and it showed the old address in Shipping Origin Addresses setting. I'm unable to load the new address to save it. When I try to search for it in the select box, it says nothing is found. In the meantime I get the banner with the message "IMPORTANT: Your TaxCloud Locations are out of sync. One or more of the addresses from your Simple Sales Tax settings are not registered as [Locations](https://taxcloud.com/go/locations/) in your TaxCloud account. Please add all of the addresses listed below on the Locations page in TaxCloud, then click Dismiss to dismiss this notice."

I tried deleting and re-adding my credentials to get it to refresh, but it doesn't seem to work. Running version 7.0.5

Please advise! Thanks!

**Comment by bporcelli** [comment]
@JoshuaC215 The best way to resolve this is to temporarily add your old business address as a Location in TaxCloud and then click the "Dismiss" button to dismiss the address mismatch notice. Once the notice is dismissed, you'll be able to sync your new address from TaxCloud by clicking the "Save changes" button on the settings page. After you've set your new origin address on the settings page you can delete the old address in TaxCloud again.

**Comment by JoshuaC215** [comment]
That did the trick! Thank you very much!
