### ISSUE TITLE
CURL Failure to calculate sales tax

### ISSUE THREAD

**Issue by blibbers** [bporcelli/simplesalestax#189]
I am having an issue where intermittently our store (shop.wretched.org) is unable to calculate sales tax and our users cannot check out. It appears to be throwing a CURL timeout error. I am able to ping and make a CURL request from the terminal on the server so it is likely not a firewall issue on either side. 

Here are some examples of my logs from WC -> Status -> Logs

`06-14-2023 @ 10:48:22 - Failed to calculate sales tax: cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to api.taxcloud.net:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 10:48:24 - Failed to calculate sales tax: cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to api.taxcloud.net:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 10:49:08 - Failed to calculate sales tax: cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to api.taxcloud.net:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 10:51:11 - Failed to calculate sales tax: cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to api.taxcloud.net:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 10:51:11 - Failed to calculate sales tax: cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to api.taxcloud.net:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 10:51:12 - Failed to calculate sales tax: cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to api.taxcloud.net:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:24:11 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:24:12 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:37:12 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:37:13 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:37:19 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:37:20 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:37:37 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:37:38 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:37:53 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
06-14-2023 @ 12:37:54 - Failed to calculate sales tax: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Do you know of any tricks I can try to get this working again? This is costing big as we have a major sale going on today.

**Comment by bporcelli** [comment]
Unfortunately this is a networking issue and not something I can help with. From prior experience with issues like this it's likely that packet loss is happening somewhere along the path between your server and TaxCloud's. You'd have to work it out with your network provider or TaxCloud (I am just a contractor and don't have access to any of their infrastructure). You may want to use WooCommerce tax rate tables as a temporary workaround to ensure tax is calculated during your sale.

Sorry I can't help you.

**Comment by blibbers** [comment]
Thanks brother. 

I reached out to Tax Cloud and they said this is a known issue with their system they are trying to work out. 

Thanks for you reply!
