### ISSUE TITLE
Path to cacert.pem is wrong in the latest version 8.0.0

### ISSUE THREAD

**Issue by vikcheema** [bporcelli/simplesalestax#205]
This issue creates a Fatal error while saving the settings of the plugin in the wp-admin. The reason is the path to the cacert.pem file is not resolving correctly. While verifying settings in the wp-admin the error can be replicated as well. 

To resolve the issue until you guys releases a fix, I applied a temporary fix.
File /wp-content/plugins/simple-sales-tax/includes/vendor/bporcelli/php-taxcloud/lib/TaxCloud/Client.php 

Line 472: 

CURLOPT_CAINFO => realpath(dirname(__FILE__) . '../../../cacert.pem'),

Replace with 

CURLOPT_CAINFO => dirname(dirname(dirname(__FILE__))) . '/cacert.pem',

This issue is only happening in the latest release 8.0.0

I hope this helps others who have updated to the latest version.

**Comment by bporcelli** [comment]
Thanks @vikcheema. This has been fixed in v8.0.1.

**Comment by vikcheema** [comment]
@bporcelli thanks for taking prompt action!
