### ISSUE TITLE
Inaccurate required field labelling and improper order creation

### ISSUE THREAD

**Issue by altered-slate** [bporcelli/simplesalestax#258]
### ISSUE SUMMARY

When a user is adding a new tax exemption form to their account, via the My Account > Exemption Certificates endpoint or while on Checkout, some fields are not marked required although they are in fact required. Additionally, which fields are in fact required changes depending on whether the certificate is being added in the My Account > Exemption Certificates context or in Checkout context, despite the form appearing the same. Under certain of these conditions, situations arise which allow creating unpaid orders. This creates confusion and a bad user experience.

### STEPS TO REPRODUCE ISSUE

**In My Account > Exemption Certificates endpoint context...**
1. Login to a WooCommerce shop as a customer
2. Navigate to My Account > Tax Exemptions
3. Click the "Add Certificate" button beneath the table (empty or containing previously added certificates)
4. Select / fill the form fields as follows:
    1. "Where does this exemption apply?" = SELECT ANY
    2. "Tax ID type" = SELECT "State Issued Exemption ID or Driver's License"
    3. "Tax ID" = ENTER ANY VALUE
    4. "Business type" = SELECT ANY
    5. "Reason for exemption" = SELECT ANY
    
    *note* - DO NOT FILL:
    - "ID issued by..." _label indicates "(optional)"_
    - Final dynamic field with element id="purchaser_exemption_reason_value" _not labelled with asterisk as required _
5. Click "Add certificate" button

**EXPECTED RESULT**
The form should submit and the certificate should be added to the user's account.

**ACTUAL RESULT**
The form is not submitted, and the omitted fields are highlighted red.
![image](https://github.com/bporcelli/simplesalestax/assets/152022721/f405dd85-7b06-4a7c-83e8-d6774d39b568)

**In Checkout context**
1. Place items in Shopping Cart and proceed to Checkout page of WooCommerce shop
2. Fill out all Checkout page sections as necessary
3. In "Tax exemption" section, select "Add new certificate" from dropdown
4. Select / fill the form fields as follows:
    1. "Where does this exemption apply?" = SELECT ANY
    2. "Tax ID type" = SELECT "State Issued Exemption ID or Driver's License"
    3. "Tax ID" = ENTER ANY VALUE
    4. "Business type" = SELECT ANY
    5. "Reason for exemption" = SELECT ANY

    *note* - DO NOT FILL:
    - "ID issued by..." _label indicates "(optional)"_
    - Final dynamic field with element id="purchaser_exemption_reason_value" _not labelled with asterisk as required _
5. Complete checkout

**EXPECTED RESULT**
Checkout should process, and assuming all shipping/payment data validated, the order should be created and the user taken to the "Thank you" page. The new tax exemption certificate should be saved in the user's account.

**ACTUAL RESULT**
Checkout appears to not process (user not taken to "Thank you" page but still on Checkout), but an unpaid order is created in the system (visible in WooCommerce admin and user's My Account > My Orders). The new tax exemption certificate is not saved in the user's account. There is an error at the top of the Checkout page reading, "An error has occurred processing your request. Please contact TaxCloud (code:409)".  The omitted fields in the "Add new certificate" form are highlighted red.
![screencapture-sprinklerhut-checkout-2024-05-29-11_22_58](https://github.com/bporcelli/simplesalestax/assets/152022721/375daf5d-9503-4ab2-bb6d-87666eab01e1)
![image](https://github.com/bporcelli/simplesalestax/assets/152022721/b9a3b735-57fb-40ce-b8e1-66e54f0596ad)
![image](https://github.com/bporcelli/simplesalestax/assets/152022721/90bedf5b-aa68-40f7-98e1-59d94e4f3259)

**ALTERNATIVE STEPS / RESULTS**
- On Checkout, perform same steps as above but select a value for "ID issued by..." field = SELECT ANY, but still keep final dynamic field with element id="purchaser_exemption_reason_value" = EMPTY
    - EXPECTED RESULTS: Same as main Checkout context ACTUAL RESULTS above
    - ACTUAL RESULTS: Checkout processes. User is taken to "Thank you" page. Order is created in system with correct payment status. Exemption certificate is saved in user's My Account > Exemption Certificates

**Comment by altered-slate** [comment]
Apologies for neglecting the basics, too focused on the forest for the trees...

Wordpress 6.5.3
WooCommerce 8.9.1
Simple Sales Tax 8.0.12

Storefront theme 4.6.0

**Comment by bporcelli** [comment]
Thanks @altered-slate! I will work on improving the labeling to properly indicate which fields are required.

**Comment by altered-slate** [comment]
@bporcelli ,

Is there any ETA on resolving the issues described above? I noticed they were added to the 8.0.13 milestone and the update shipped, but after installing it the problems are still the same. This was somewhat expected since I didn't see any reference to the issues in the 8.0.13 changelog. 

By the way, I'm also curious if the matter of orders being improperly placed can also be acknowledged:
> ACTUAL RESULT
> Checkout appears to not process (user not taken to "Thank you" page but still on Checkout), but an unpaid order is created in the system (visible in WooCommerce admin and user's My Account > My Orders). The new tax exemption certificate is not saved in the user's account. There is an error at the top of the Checkout page reading, "An error has occurred processing your request. Please contact TaxCloud (code:409)". The omitted fields in the "Add new certificate" form are highlighted red.
I know you mentioned that you'll work on improving required field indicators, but this is not merely related to presentation and relates to pre order processing validation.

**Comment by bporcelli** [comment]
@altered-slate Just pushed out a release with a fix for this. Sorry for the delay!
