### ISSUE TITLE
Ask users for reviews

### ISSUE THREAD

**Issue by bporcelli** [bporcelli/simplesalestax#45]
In order to improve our visibility and encourage more people to download SST, we should ask users to review Simple Sales Tax on WP.org. It's pretty typical for plugins to do this after the user has had some time to explore the plugin. In our case, I think asking the user to leave a review after SST has calculated the tax for more than a certain number of orders (maybe 5) would make sense. A modified, perhaps less personalized, version of the notice that EDD Quaderno uses to ask for reviews (depicted below) would probably work.

![Screenshot_2020-01-04 Dashboard ‹ Skyld Staging — WordPress](https://user-images.githubusercontent.com/5545098/71768456-046e9a80-2ee4-11ea-923d-06b74c900d0d.png)

**Comment by taxcloud** [comment]
Can we implement the webhooks for activation and deactivation? If there is a webhooks for download that would be good too.

**Comment by bporcelli** [comment]
I'm not aware of any TaxCloud webhooks, but firing activation and
deactivation events should be possible. That being said we should have this
discussion on a separate issue. This is about asking users to review the
plugin on WP.org so more people download it.

**Comment by bporcelli** [comment]
Won't do for now.
