### ISSUE TITLE
Can I add unique origin addresses to each variation of a variable product?

### ISSUE THREAD

**Issue by olsoner** [bporcelli/simplesalestax#50]
Is there a way that I can create a variable product in Simple Sales Tax For Woocommerce with multiple variations and have each variation ship from unique origin addresses that do not change?

I have a digital download I would like to sell and tax from my primary address, and a drop shipped non-downloadable of the same product that ships from another state?  Can this be done? 

Something similar to the unique TIC would be nice.

Thanks,

**Comment by bporcelli** [comment]
Hi @olsoner,

It is not possible to do this out of the box and likely will not be for some time. However, you can implement something like this yourself with the help of the `wootax_origin_address` filter: https://github.com/bporcelli/simplesalestax/blob/master/includes/abstracts/class-sst-abstract-cart.php#L376

Let me know if you have any questions.
